# Default values for vault-consul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

consul:
  image: "consul:1.8.2"
  # Choose an optional name for the datacenter
  
  datacenter: consul-demo-01

  # Enable the Consul Web UI via a NodePort
  ui:
    service:
      type: 'NodePort'

  # Enable Connect for secure communication between nodes
  connectInject:
    enabled: true

  client:
    enabled: true

  # Use only one Consul server for local development
  server:
    replicas: 1
    bootstrapExpect: 1
    disruptionBudget:
      enabled: true
      maxUnavailable: 0

  syncCatalog:
    enabled: true


vault:
  server:
    image:
      repository: "vault"
      tag: "1.4.2"
      # Overrides the default Image Pull Policy
      pullPolicy: IfNotPresent
    
  affinity: ""
  ha:
    enabled: true
